### ISSUE TITLE
Error Installing MUSE-MICO

### ISSUE THREAD

**Issue by rafaloz** [CBICA/MICO#1]
Hello, 

I am installing MUSE in my computer. One of the dependencies is MICO, however when I try to build it with cmake It does not recognizes NiftiCLib installed. I have NiftiCLib 2.0.0 installed in my computer and I have installed other software based upon it from CBICA...

**Comment by jammy270** [comment]
Hi @rafaloz,

Are you using `tags/1.1.0` for this? If not, could you please try that and see if that resolves the issue?

**Comment by rafaloz** [comment]
I am adding the folder nifticlib-2.0.0 with the built elements in /lib /include /bin but it still does not recognize it in the configuration. Also I installed it in my home directory

**Comment by jammy270** [comment]
Cool! If you are installing from `tags/1.1.0`, you don't need to do any of that. Can you try installing from [https://github.com/CBICA/MICO/tree/1.1.0](url) and report if you have any issues?

**Comment by rafaloz** [comment]
No issues! thank you!
