### ISSUE TITLE
Missing /include/mico/basis.h when installing.

### ISSUE THREAD

**Issue by KakkiDaisuki** [CBICA/MICO#2]
**Describe the question**
I am able to finish the configuration using CMake. But when building the software using _$ make_, an error shows up saying that there is a missing file /mico/basis.h. 

**Screenshots**
![image](https://user-images.githubusercontent.com/94285213/212575589-5f9c6405-3cc2-436f-8a91-5f4f03f553c0.png)

**System**
WSL2 Ubuntu 20.04

Hi @sarthakpati! Thank you very much for posting the MICO method codes, and it looks like here is the only place I could find them as SBIA was renamed and the old web has been canceled. As shown in the screenshot, I would like to know if this /mico/basis.h is the file I should generate by some method or if you could generously instruct me on how to get it.

Best Regards,
Junhua

**Comment by sarthakpati** [comment]
Hi @KakkiDaisuki, you need to ensure you follow [the installation instructions](https://github.com/CBICA/MICO/blob/master/INSTALL.txt). In this case, [Basis](https://github.com/CBICA/MICO/blob/master/INSTALL.txt#L58) (an underlying dependency) doesn't seem to have been installed.

**Comment by KakkiDaisuki** [comment]
Hi @sarthakpati , I think I have installed the BASIS (following the instructions from [HOME-BASIS](https://cmake-basis.github.io/index.html), the SBIA link provided in the instruction is invalid now). And when configuring the MICO, the BASIS_DIR could also be automatically detected:
![image](https://user-images.githubusercontent.com/94285213/212757463-61996dc6-7051-4928-9e47-23101f9ce4c0.png)
When installing the [DRAMMS](https://www.nitrc.org/projects/dramms ), the BASIS is also detected and the installation was successful. 

The error says the missing basis.h is under MICO/include/mico/, which is the directory within the MICO installation package:
![image](https://user-images.githubusercontent.com/94285213/212758930-bbd43ead-bf7b-4ed3-8759-7ddbf22d0372.png)

Based on these, I think it might not be the problem of BASIS. Could you please give some hints on how to construct this MICO/include/mico/basis.h? I might have asked a ridiculous question as I am a rookie in Linux development, and I am very sorry for this.

**Comment by sarthakpati** [comment]
Can you try installing BASIS from [this repo](https://github.com/CBICA/basis/tree/2.1.4), instead?

**Comment by KakkiDaisuki** [comment]
Changing to BASIS Ver.2.1.4 from the link could help solve this issue, thank you very much! But then a new issue emerges:
![image](https://user-images.githubusercontent.com/94285213/212848295-710578fa-60fd-45e7-ad4a-9ddc05d9f7a2.png)

I then turned to use the distribution set at [MICO 1.1.0](https://github.com/CBICA/MICO/tree/1.1.0), which worked without any error reported.  But the installation would only produce a single file called **mico** (~400kb) under **/MICO/bin/,**, may I know if it is what to expect?

Really appreciate your help!

**Comment by sarthakpati** [comment]
Hey, I was never really part of this project and I'm helping out as a favor. Could you please post a new issue with details (including the compiler you are using)?
